Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/python_for_food_scientists-OgywevK--py3.9/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/runner/.cache/pypoetry/virtualenvs/python_for_food_scientists-OgywevK--py3.9/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.cache/pypoetry/virtualenvs/python_for_food_scientists-OgywevK--py3.9/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/runner/.cache/pypoetry/virtualenvs/python_for_food_scientists-OgywevK--py3.9/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/runner/.cache/pypoetry/virtualenvs/python_for_food_scientists-OgywevK--py3.9/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.cache/pypoetry/virtualenvs/python_for_food_scientists-OgywevK--py3.9/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.cache/pypoetry/virtualenvs/python_for_food_scientists-OgywevK--py3.9/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
third_array = np.arange(3,10)
first_array < third_array
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[41], line 2[0m
[1;32m      1[0m third_array [38;5;241m=[39m np[38;5;241m.[39marange([38;5;241m3[39m,[38;5;241m10[39m)
[0;32m----> 2[0m [43mfirst_array[49m[43m [49m[38;5;241;43m<[39;49m[43m [49m[43mthird_array[49m

[0;31mValueError[0m: operands could not be broadcast together with shapes (4,) (7,) 
ValueError: operands could not be broadcast together with shapes (4,) (7,) 

